/*  BIOS KEYBOARD SCAN CODES  */

#define  ESC      0x01
#define  ONE      0x02
#define  TWO      0x03
#define  THREE    0x04
#define  FOUR     0x05
#define  FIVE     0x06
#define  SIX      0x07
#define  SEVEN    0x08
#define  EIGHT    0x09
#define  NINE     0x0a
#define  ZERO     0x0b

#define  UP       0x48
#define  DOWN     0x50
#define  PGUP     0x49
#define  PGDOWN   0x51
#define  HOME     0x47
#define  END      0x4f


#define  LQ  0x10
#define  LW  0x11
#define  LE  0x12
#define  LR  0x13
#define  LT  0x14
#define  LY  0x15
#define  LU  0x16
#define  LI  0x17
#define  LO  0x18
#define  LP  0x19
#define  LBRACE  0x1a
#define  RBRACE  0x1b

#define  LA  0x1e
#define  LS  0x1f
#define  LD  0x20
#define  LF  0x21
#define  LG  0x22
#define  LH  0x23
#define  LJ  0x24
#define  LK  0x25
#define  LL  0x26
#define  SEMICOLON  0x27
#define  APOSTROPHY  0x28

#define  LZ  0x2c
#define  LX  0x2d
#define  LC  0x2e
#define  LV  0x2f
#define  LB  0x30
#define  LN  0x31
#define  LM  0x32

