//*****************[  FUNCTION PROTOTYPES for PAL.C  ]****************
void far Black_Pal( void );
void far FadeIn( char far * palette, int speed );
void far FadeOut( char far * palette, int speed );
void far FadeToRed( char far * palette, int speed );
//void RGB2Red( char far * palette );
//void RGB2Green( char far * palette );
//void RGB2Blue( char far * palette );
//void Fade_Darker( char far * palette , int amount , int speed);
